### ISSUE TITLE
RS485 to UART converter hookup configuration

### ISSUE THREAD

**Issue by DarekKrawczyk** [emansarahafi/MoniCropHardware#1]
Hello, could you describe how to hook up an RS485 to UART converter to an RPi? I can see you are using USB 2.0, but I am wondering how you are physically doing that (I am especially interested in the DI, DE, RE, and RO pins). Are you using some IC module for that? I have such a setup (besides ESP, I don't care for that), and I would like to recreate what you have done in terms of communicating with the RPi with a soil sensor, but I can't wrap my head around it. Thank you!

**Comment by emansarahafi** [comment]
Hello, thank you for interest in my project, I actually purchased from Amazon a RS485 to USB converter, which facilitated the communication between the RPI & the soil sensor.

I do have an alternative circuit design using the RS485 module, I have attached the picture here, but you may have to edit the code accordingly as mine involved using a RS485 to USB converter instead of an IC module :)

![CMPE 495B1_bb](https://github.com/emansarahafi/MoniCropHardware/assets/85173630/ab4230fa-a350-4142-92c9-32eab78c8314)
